cmake_minimum_required (VERSION 3.8)

project(sockets LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable (sockets "program.cpp")
add_executable (udpserver "udp_server.cpp")
add_executable (udpclient "udp_client.cpp")
add_executable (udpMulticastSender "udp_multicast_sender.cpp")

set_property(TARGET sockets PROPERTY CXX_STANDARD 17)
set_property(TARGET udpserver PROPERTY CXX_STANDARD 17)
set_property(TARGET udpclient PROPERTY CXX_STANDARD 17)
set_property(TARGET udpMulticastSender PROPERTY CXX_STANDARD 17)